base_url = "https://myogg.github.io/"
generate_feeds = true
feed_filenames = ["rss.xml"]
theme = "even"
taxonomies = [
    {name = "categories", feed = true},
    {name = "tags", feed = true},
]
[extra]
even_title = "meektion's Blog"
even_menu = [
    {url = "$BASE_URL", name = "Home"},
    {url = "$BASE_URL/tags/", name = "Tag"},
    {url = "$BASE_URL/issue-7/", name = "About"},
    {url = "$BASE_URL/issue-33/", name = "link"},
]
