name: Deploy Static Content to GitHub Pages

on:
  issues:
    types:
      - opened
      - edited
      - closed
      - reopened
      - labeled
      - unlabeled
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} # 使用secrets存储token以提高安全性
      ISITE_VERSION: v0.1.3
      ZOLA_VERSION: v0.19.2
      OWNER: ${{ github.repository_owner }} # 更改变量名以提高可读性
      REPO_NAME: ${{ github.event.repository.name }} # 更改变量名以提高可读性
      BASE_URL: >- # 使用>-来保持长URL字符串的整洁
        https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}
        # 如果需要自定义域名，请取消下面一行的注释并注释掉上面一行
        # https://myogg.github.io/gitblog/

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3 # 更新到最新版本

      - name: Download and Install isite
        run: |
          gh release download $ISITE_VERSION --repo kemingy/isite -p '*Linux_x86_64*' --output isite.tar.gz
          tar -zxf isite.tar.gz && sudo mv isite /usr/local/bin

      - name: Generate Markdown with isite
        run: |
          isite generate --user $OWNER --repo $REPO_NAME

      - name: Download and Install Zola
        run: |
          gh release download $ZOLA_VERSION --repo getzola/zola -p '*linux*' --output zola.tar.gz
          tar -zxf zola.tar.gz && sudo mv zola /usr/local/bin

      - name: Build Zola Site
        run: |
          cp config.toml output/config.toml
          cd output && zola build --base-url $BASE_URL

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v1 # 注意：configure-pages的最新版本可能不同，请检查GitHub Marketplace

      - name: Upload Public Directory
        uses: actions/upload-pages-artifact@v1 # 注意：upload-pages-artifact的最新版本可能不同，通常与configure-pages配套使用
        with:
          path: output/public

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/github-pages-deploy-action@v1 # 使用更具体的Actions进行部署，注意版本号可能不同
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages # 确保部署到正确的分支
          folder: output/public # 确保上传正确的文件夹
