name: Deploy static content to Pages

on:
  issues:
    types:
      - opened
      - edited
      - closed
      - reopened
      - labeled
      - unlabeled
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
      ISITE_VERSION: v0.1.3
      ZOLA_VERSION: v0.19.2
      USER: ${{ github.repository_owner }}
      REPO: ${{ github.event.repository.name }}
      # BASE_URL should be set dynamically if deploying to GitHub Pages
      # BASE_URL: https://blog.yihong0618.me # remove or comment out this line

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download and install isite
        run: |
          gh release download $ISITE_VERSION --repo kemingy/isite -p '*Linux_x86_64*' --output isite.tar.gz
          tar zxf isite.tar.gz && sudo mv isite /usr/local/bin

      - name: Generate markdown with isite
        run: |
          isite generate --user $USER --repo $REPO

      - name: Download and install Zola
        run: |
          gh release download $ZOLA_VERSION --repo getzola/zola -p '*linux*' --output zola.tar.gz
          tar zxf zola.tar.gz && sudo mv zola /usr/local/bin

      - name: Build static site with Zola
        run: |
          cp config.toml output/config.toml
          cd output && zola build --base-url "https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output/public
          # Other options can be set here, such as cname or force_orphan

      # Note: The URL of the deployed pages will be automatically available in the repository's Pages settings
      # and can also be found in the logs of this step. You cannot set it directly in the environment.url.
